### ISSUE TITLE
Is there have a static gdb with python support or how to compile it?

### ISSUE THREAD

**Issue by sucof** [pwndbg/gdb-prebuilt#1]
Hi, Is there have a static gdb with python support? I want to compile it, but failed, my commands are below:
```
/configure --with-python --prefix="/root/build_gdb/gdb-8.2/build" CXXFLAGS='-fPIC -static' CFLAGS='-fPIC -static 
make
```
the error is: configure: error: python is missing or unusable.
but I have install python-dev.
Can you help me?
Thanks.

**Comment by zachriggle** [comment]
The included [gdb-build.sh](https://github.com/pwndbg/gdb-prebuilt/blob/master/gdb-build.sh) can be used for building GDB from source.

To my knowledge, it is **not possible** to have a **statically linked GDB** which also includes **support for Python**, since `libpython.so` and friends cannot be loaded (because it's statically linked).
